cluster:
  bgpInstances:
    cluster:
      localASN: 65002
      peers:
        tor:
          peerASN: 65001

loadBalancer:
  ipPools:
    loadbalancer:
      enabled: true
      blocks:
        public:
          enabled: true
          cidr: 172.29.0.0/28
