apiVersion: v2
name: bgp-loadbalancing
description: A Helm chart to enable BGP load balancing via Cilium.
icon: https://www.noction.com/wp-content/uploads/2024/04/BGP-states.png
type: application
version: 0.1.0
appVersion: "0.1.0"
